### ISSUE TITLE
On Firefox, zooming occurs to the right of the point the user clicks

### ISSUE THREAD

**Issue by wenderen** [jblang/XaoSjs#3] opened 2015-03-08 19:42 UTC
To reproduce:
1. Open http://jblang.github.io/XaoSjs/
2. Click anywhere in the fractal. The bug is most noticeable when you click in the left half of the fractal.
3. Observe that the fractal does zoom, but towards a point located to the right of the clicked point.

Notes:
1. Version: FF36, OS: Ubuntu Trusty
2. This behaviour was not observed on Chrome (Chrome 40, same OS)

**Comment by wenderen** [comment] 2015-03-08 19:46
Also, if you'll allow it, I'd like to work on fixing this bug.

**Comment by wenderen** [comment] 2015-03-12 23:27
The bug is also there on FF36 on Windows. It doesn't manifest when I download and open the html file in a browser, though.

**Comment by jblang** [comment] 2015-06-19 10:36
Hi, and sorry for the late response. If you can fix this, I'd be more than happy to accept a pull request.  Please make sure you're working on the latest code from master. I've recently updated the project to use bootstrap.

**Comment by jblang** [comment] 2015-09-20 15:56
I'm closing this because I've made some changes and this works when I tested my latest code on the current version of Firefox.  If you still have problems, please open a new bug with instructions to reproduce using the latest commit.

**Closed by jblang** 2015-09-20 15:56 UTC
